# require "bundler/gem_tasks"
# require 'rake/testtask'

# Rake::TestTask.new do |t|
#   t.libs << "test" << "."
#   t.test_files = FileList['test/test*.rb']
#   t.verbose = false
# end

require 'rspec/core/rake_task'

desc 'run the example specs'
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.rspec_opts = ['--options', 'spec/rspec.opts']
end

desc 'run the examples'
task :examples do
  load 'prelude_lambda.rb'
end

task default: [:spec, :examples]